### ISSUE TITLE
Is it possible to launch among different machines?

### ISSUE THREAD

**Issue by kaih70** [jeffreysijuntan/CryptGPU#2]
I found launcher scripts for multiprocess and aws.
I have multiple machines and I would like to benchmark CryptGPU among them.
Any advice?

**Comment by jeffreysijuntan** [comment]
Yes. The `aws_launcher.py` script can be modified to run CryptGPU your own servers. I just commited two files `launch_distributed.sh` and `distributed_launcher.py` that can help you run our system on multiple machines. You need to go to `distributed_launcher.py` to set your username, hostname, password, and master_ip_address (ip address of one of your machine). Let me know if the script helps address your issue.

**Comment by kaih70** [comment]
Actually I installed CryptGPU inside docker containers, and I ran `run_command` directly inside each container respectively.
It works, so I guess `launch_distributed.sh` may also run nicely.
Thank you!
